version: "3.3"

services:
  web:
    build: .
    ports:
      - "5000:80"
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: enrolments
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata